"""create market observations and collection runs

Revision ID: 5cd56fc16046
Revises: 
Create Date: 2026-09-09 20:54:54.300236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cd56fc16046'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('source_reference', sa.String(length=128), nullable=False),
    sa.Column('collector', sa.String(length=255), nullable=False),
    sa.Column('collector_version', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_collection_runs_source_started', 'collection_runs', ['source_id', 'source_reference', 'started_at'], unique=False)
    op.create_table('market_observations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('indicator_code', sa.String(length=64), nullable=False),
    sa.Column('reference_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('source_reference', sa.String(length=128), nullable=False),
    sa.Column('collector', sa.String(length=255), nullable=False),
    sa.Column('collector_version', sa.String(length=32), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicator_code', 'source_id', 'reference_date', 'value', name='uq_market_observation_identity_and_value')
    )
    op.create_index('ix_market_observations_indicator_reference', 'market_observations', ['indicator_code', 'reference_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_market_observations_indicator_reference', table_name='market_observations')
    op.drop_table('market_observations')
    op.drop_index('ix_collection_runs_source_started', table_name='collection_runs')
    op.drop_table('collection_runs')
    # ### end Alembic commands ###
